### ISSUE TITLE
How do you install kernel headers? 

### ISSUE THREAD

**Issue by TeddyBeer1983** [retuxx/hid-retrobit#5]
Hello, 

I'm trying to install the driver and it tells me that some the kernel drivers aren't found.

How do I fix this?

**Comment by msteinbeck** [comment]
Which distribution are you using?

**Comment by TeddyBeer1983** [comment]
4.1.19-v7

**Comment by TeddyBeer1983** [comment]
And I'm on a raspberry pi

**Comment by msteinbeck** [comment]
Maybe [this](https://github.com/retuxx/hid-retrobit/issues/4) is a good starting point for you. @jonnypage managed to install the driver on a raspberry pi.

**Comment by TeddyBeer1983** [comment]
Ok you can close it now. I managed to make it work.

**Comment by msteinbeck** [comment]
Nice. Maybe you could write a short howto? That would be kind :).

**Comment by jonnypage** [comment]
It was my friend's adapter for his retropie install. I should borrow the retrobit adapter from him and write up a how to. I totally forget how I did it, and don't have the adapter anymore :(

**Comment by espenoh** [comment]
I had the same problem on my Pi3 running RetroPie/Raspbian 4.4.13-v7+. After trying way too long with the "normal" linux header packages and some wonky scripts I eventually discovered that there now is a brand new package just for this.

So to fix it:
`sudo apt-get install raspberrypi-kernel-headers` 
and run the normal steps (install dkms and the deb-file itself).

Now my Genesis controllers have all the d-pad directions working again!

**Comment by msteinbeck** [comment]
Thanks for the info. I will add it to the REAMDE.md.
